docs_dir: docs/book
site_dir: docs/html
extra:
    project: Mezzio
    installation:
      config_provider_class: 'Mezzio\Hal\ConfigProvider'
    current_version: v2
    versions:
      - v2
      - v1
nav:
    - Home: index.md
    - v2:
      - Introduction: v2/index.md
      - Installation: v2/installation.md
      - "Hypertext Application Language": v2/hal.md
      - "Links and Resources": v2/links-and-resources.md
      - "Generating Resources":
        - "Generating Resources from PHP Objects": v2/resource-generator.md
        - "Generating HAL for Doctrine Entities": v2/doctrine.md
      - "Generating Representations": v2/representations.md
      - "Provided Factories": v2/factories.md
      - Cookbook:
          - "Generating Custom Resources": v2/cookbook/generating-custom-resources.md
          - "Generating Custom Links In Middleware and Request Handlers": v2/cookbook/generating-custom-links-in-middleware.md
          - "Using the ResourceGenerator in Path-Segregated Middleware": v2/cookbook/path-segregated-uri-generation.md
      - Migration:
          - "Migration From Version 1": v2/migration.md
    - v1:
      - Introduction: v1/index.md
      - "Hypertext Application Language": v1/hal.md
      - "Links and Resources": v1/links-and-resources.md
      - "Generating Resources":
        - "Generating Resources from PHP Objects": v1/resource-generator.md
        - "Generating HAL for Doctrine Entities": v1/doctrine.md
      - "Generating Representations": v1/representations.md
      - "Provided Factories": v1/factories.md
      - Cookbook:
          - "Generating Custom Resources": v1/cookbook/generating-custom-resources.md
          - "Generating Custom Links In Middleware and Request Handlers": v1/cookbook/generating-custom-links-in-middleware.md
          - "Using the ResourceGenerator in Path-Segregated Middleware": v1/cookbook/path-segregated-uri-generation.md
    - "_hidden-legacy-page-links":
      - '_intro': intro.md
      - '_reference_hal': hal.md
      - '_reference_links_and_resources': links-and-resources.md
      - '_reference_generating_resources': resource-generator.md
      - '_reference_custom_resources': cookbook/generating-custom-resources.md
      - '_reference_representations': representations.md
      - '_reference_generating_hal_for_doctrine_entities': doctrine.md
      - '_reference_factories': factories.md
      - '_cookbook_generating_custom_links_in_middleware_and_request_handlers': cookbook/generating-custom-links-in-middleware.md
      - '_cookbook_using_the_resourcegenerator_in_path-segregated_middleware': cookbook/path-segregated-uri-generation.md
site_name: mezzio-hal
site_description: 'Hypertext Application Language for PSR-7 Applications'
repo_url: 'https://github.com/mezzio/mezzio-hal'
